/* VALIDATION */
const TABLE_VALIDATE = "TABLE/VALIDATE";
const ROW_VALIDATE = "ROW/VALIDATE";

/* UPDATE VALUES */
const TABLE_CLEAN = "TABLE/CLEAN";
const TABLE_UPDATE = "TABLE/UPDATE";
const CELL_VALUE_UPDATE = "CELL_VALUE/UPDATE";
const AXIS_VALUE_UPDATE = "AXIS_VALUE/UPDATE";

/* ADD/REMOVE ACTIONS */
const ROW_ADD = "ROW/ADD";
const ROW_REMOVE = "ROW/REMOVE";
const AXIS_ADD = "COLUMN/ADD";
const AXIS_REMOVE = "COLUMN/REMOVE";

export const actionTypes = {
    TABLE_VALIDATE,
    ROW_VALIDATE,
    TABLE_CLEAN,
    TABLE_UPDATE,
    CELL_VALUE_UPDATE,
    AXIS_VALUE_UPDATE,
    ROW_ADD,
    ROW_REMOVE,
    AXIS_ADD,
    AXIS_REMOVE,
};